spring.application.name=spring-boot-service-boilerplate
jwt.secret=

## Postgresql
# spring.datasource.url=
# spring.datasource.username=
# spring.datasource.password=
# spring.datasource.driverClassName=org.postgresql.Driver

## Sqlite
# spring.datasource.driverClassName=org.sqlite.JDBC
# spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
## memory based
## spring.datasource.url=jdbc:sqlite:/tmp/mydb.sqlite
# file based
# spring.datasource.url=jdbc:sqlite:memory:myDb?cache=shared